version: "3"
services:
  app:
    image: registry.cn-beijing.aliyuncs.com/codeforfun/xxl-job-modify:2.1.0
    build: .
    environment:
      MYSQL_PASSWORD: root
    ports:
      - "8080:8080"
  mysql:
    image: mysql:5.7.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"